spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  datasource:
    url: jdbc:h2:mem:hodolog;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
  sql:
    init-model: always

#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true


hodolog:
  hello: "world"