spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  datasource:
    url: jdbc:h2:mem:hodolog
    username: sa
    password:

#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true